# Generated by Django 3.0.4 on 2020-04-24 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Label of framework, library, language etc.')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Keywords of the post')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['isDone', '-created_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Showcase Name')),
                ('brief', models.CharField(max_length=200, verbose_name='A brief of the showcase')),
                ('about', models.TextField(verbose_name='About the showcase')),
                ('link_online', models.CharField(max_length=300, verbose_name='Link to online presence')),
                ('link_github', models.CharField(max_length=300, verbose_name='Link to GitHub')),
                ('link_codesandbox', models.CharField(max_length=300, verbose_name='Link to CodeSandbox')),
                ('img_front', models.ImageField(blank=True, null=True, upload_to='showcase_images', verbose_name='Image (size: 600px x 400px) to show on the front of the card')),
                ('img_back', models.ImageField(blank=True, null=True, upload_to='showcase_images', verbose_name='Image (size: 600px x 400px) to show on the back of the card')),
                ('img_third', models.ImageField(blank=True, null=True, upload_to='showcase_images', verbose_name='Image (size: 600px x 400px) to show in detail page (optional)')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Label')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tech', verbose_name='A list for technical sheet')),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post Title')),
                ('content', models.TextField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-uploaded_date', 'title'],
            },
        ),
    ]
