# Generated by Django 3.0.4 on 2020-04-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200424_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='label',
            field=models.ManyToManyField(blank=True, to='api.Label'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='tech',
            field=models.ManyToManyField(blank=True, to='api.Tech', verbose_name='A list for technical sheet'),
        ),
    ]
