# Generated by Django 3.0.4 on 2020-04-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200424_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='link_codesandbox',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link to CodeSandbox'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='link_github',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link to GitHub'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='link_online',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link to online presence'),
        ),
    ]
