# Generated by Django 3.0.4 on 2020-04-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200424_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='tech',
            new_name='techs',
        ),
    ]
